springdoc:
  swagger-ui:
    path: /api/swagger-ui.html
    enabled: true
  api-docs.path: /api/docs
  packagesToScan: com.raul.demoopenapi
  pathsToMatch: /**
spring:
  api:
    common:
      version: 1.0.0
      title: Sample Api
      description: Description of the api...
      termsOfService: MY TERMS OF SERVICE
      license: MY LICENSE
      licenseUrl: LICENSE URL
      externalDocDesc: MY WIKI PAGE
      externalDocUrl: My WIKI URL
      contact:
        name: NAME OF CONTACT
        url: URL TO CONTACT
        email: contact@gmail.com
  application:
    name: demoopenapi
  datasource:
    url: jdbc:sqlite:test.db
    driver-className: org.sqlite.JDBC
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update

server.port: 7999

server:
  forward-headers-strategy: framework
  use-forward-headers: true